services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    command:
      - -js
      # Debugging
      - -DV

  eventstoredb:
    image: eventstore/eventstore:latest
    ports:
      - "2113:2113"
      - "1113:1113"
    command:
      - --insecure
      - --enable-external-tcp
      - --enable-atom-pub-over-http
      # https://hexdocs.pm/commanded/choosing-an-event-store.html#running-eventstoredb
      - --run-projections=All
      - --start-standard-projections=true
